// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"time"
)

type Hotel struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Address   string    `json:"address"`
	Location  string    `json:"location"`
	CreatedAt time.Time `json:"created_at"`
}

type Rate struct {
	HotelID   sql.NullInt64 `json:"hotel_id"`
	RoomID    int64         `json:"room_id"`
	Rate      int32         `json:"rate"`
	CreatedAt time.Time     `json:"created_at"`
}

type Reservation struct {
	ID        int64         `json:"id"`
	HotelID   sql.NullInt64 `json:"hotel_id"`
	RoomID    int64         `json:"room_id"`
	StartDate time.Time     `json:"start_date"`
	EndDate   time.Time     `json:"end_date"`
	Status    int32         `json:"status"`
	UserID    sql.NullInt64 `json:"user_id"`
	CreatedAt time.Time     `json:"created_at"`
}

type Room struct {
	ID          int64     `json:"id"`
	RoomTypeID  int64     `json:"room_type_id"`
	HotelID     int64     `json:"hotel_id"`
	IsAvailable int64     `json:"is_available"`
	Status      int64     `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
}

type RoomInventory struct {
	HotelID        int64     `json:"hotel_id"`
	RoomID         int64     `json:"room_id"`
	RoomTypeID     int64     `json:"room_type_id"`
	Date           time.Time `json:"date"`
	TotalInventory int32     `json:"total_inventory"`
	TotalReserved  int32     `json:"total_reserved"`
	CreatedAt      time.Time `json:"created_at"`
}

type RoomType struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID                int64     `json:"id"`
	Username          string    `json:"username"`
	HashedPassword    string    `json:"hashed_password"`
	FullName          string    `json:"full_name"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}
