// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	CreateHotel(ctx context.Context, arg CreateHotelParams) (Hotel, error)
	CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error)
	DeleteHotel(ctx context.Context, id int64) error
	DisableRoom(ctx context.Context, arg DisableRoomParams) error
	GetHotel(ctx context.Context, id int64) (Hotel, error)
	GetRoomByHotelId(ctx context.Context, dollar_1 interface{}) (Room, error)
	ListHotels(ctx context.Context, arg ListHotelsParams) ([]Hotel, error)
	UpdateHotel(ctx context.Context, arg UpdateHotelParams) (Hotel, error)
	UpdateRoom(ctx context.Context, arg UpdateRoomParams) error
}

var _ Querier = (*Queries)(nil)
