// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: room_inventory.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createRoomInventory = `-- name: CreateRoomInventory :one
INSERT INTO room_inventory (hotel_id,
                   room_id,
                   room_type_id,
                   date,
                   total_inventory,
                   total_reserved) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING hotel_id, room_id, room_type_id, date, total_inventory, total_reserved, created_at
`

type CreateRoomInventoryParams struct {
	HotelID        int64     `json:"hotel_id"`
	RoomID         int64     `json:"room_id"`
	RoomTypeID     int64     `json:"room_type_id"`
	Date           time.Time `json:"date"`
	TotalInventory int32     `json:"total_inventory"`
	TotalReserved  int32     `json:"total_reserved"`
}

func (q *Queries) CreateRoomInventory(ctx context.Context, arg CreateRoomInventoryParams) (RoomInventory, error) {
	row := q.db.QueryRowContext(ctx, createRoomInventory,
		arg.HotelID,
		arg.RoomID,
		arg.RoomTypeID,
		arg.Date,
		arg.TotalInventory,
		arg.TotalReserved,
	)
	var i RoomInventory
	err := row.Scan(
		&i.HotelID,
		&i.RoomID,
		&i.RoomTypeID,
		&i.Date,
		&i.TotalInventory,
		&i.TotalReserved,
		&i.CreatedAt,
	)
	return i, err
}

const listRoomInventory = `-- name: ListRoomInventory :many
SELECT hotel_id, room_id, room_type_id, date, total_inventory, total_reserved, created_at FROM room_inventory
WHERE hotel_id = COALESCE($1, hotel_id) AND (room_id = COALESCE($2, room_id))
ORDER BY $1
LIMIT $4
OFFSET $3
`

type ListRoomInventoryParams struct {
	HotelID sql.NullInt64 `json:"hotel_id"`
	RoomID  sql.NullInt64 `json:"room_id"`
	Offset1 int32         `json:"offset1"`
	Page    int32         `json:"page"`
}

func (q *Queries) ListRoomInventory(ctx context.Context, arg ListRoomInventoryParams) ([]RoomInventory, error) {
	rows, err := q.db.QueryContext(ctx, listRoomInventory,
		arg.HotelID,
		arg.RoomID,
		arg.Offset1,
		arg.Page,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoomInventory
	for rows.Next() {
		var i RoomInventory
		if err := rows.Scan(
			&i.HotelID,
			&i.RoomID,
			&i.RoomTypeID,
			&i.Date,
			&i.TotalInventory,
			&i.TotalReserved,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoomInventory = `-- name: UpdateRoomInventory :one
UPDATE room_inventory
SET
    date = $3,
    total_inventory = $4,
    total_reserved = $5
WHERE hotel_id = $1 and room_id = $2
RETURNING hotel_id, room_id, room_type_id, date, total_inventory, total_reserved, created_at
`

type UpdateRoomInventoryParams struct {
	HotelID        int64     `json:"hotel_id"`
	RoomID         int64     `json:"room_id"`
	Date           time.Time `json:"date"`
	TotalInventory int32     `json:"total_inventory"`
	TotalReserved  int32     `json:"total_reserved"`
}

func (q *Queries) UpdateRoomInventory(ctx context.Context, arg UpdateRoomInventoryParams) (RoomInventory, error) {
	row := q.db.QueryRowContext(ctx, updateRoomInventory,
		arg.HotelID,
		arg.RoomID,
		arg.Date,
		arg.TotalInventory,
		arg.TotalReserved,
	)
	var i RoomInventory
	err := row.Scan(
		&i.HotelID,
		&i.RoomID,
		&i.RoomTypeID,
		&i.Date,
		&i.TotalInventory,
		&i.TotalReserved,
		&i.CreatedAt,
	)
	return i, err
}
