name: ci-test

# We can define how it will be triggered using the on keyword.
on:
  push:
    branches: [ "main" ]

jobs:
  # job 1
  test:
    name: Test
    runs-on: ubuntu-latest

    # Multiple step for job 1
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.20

      - name: Test
        run: make test
