name: ci-test

# We can define how it will be triggered using the on keyword.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # job 1
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: booking_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    # Multiple step for job 1
    steps:
      # Checkout code
      - uses: actions/checkout@v3

      # Install Go
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.20

      # Get dependencies
      - name: Install golang-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.17.0/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/bin/migrate
          which migrate

      - name: Run migrations
        run: make migrateup

      # Run the tests
      - name: Test
        run: make test
